### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by Artem212** [Leemellaret/AbstractMachine#1]
1) Домен должен быть IEnumerable
2) Операция добавления элемента в домен.
3) Удаление элемента из домена.
4) RangeDomain не может быть доменом. Могу предложить добавить туда шаг, тогда можно будет получить конечное число элементов.(не срочно)
5) Операции над доменами (пересечение, объединение и тд) (не срочно)
Пункты 1-3 желательно сделать сегодня

**Comment by Leemellaret** [comment]
1, 2, 3 сделано.
Про 4 хотел бы услышать поподробнее.
5 в работе.

**Comment by Leemellaret** [comment]
5 готово

**Comment by Leemellaret** [comment]
4 готово
