### ISSUE TITLE
Abstract Machine

### ISSUE THREAD

**Issue by Artem212** [Leemellaret/AbstractMachine#2]
Помнить инициальное состояние

**Comment by Leemellaret** [comment]
Зачем? Инициальное состояние можно хранить вне автомата. По идее автомату совершенно незачем хранить его

**Comment by Artem212** [comment]
Согласно математической модели инициальный автомат это пятерка объектов. Среди них есть инициальное состояние. Вполне логично что инициальный автомат знает своё инициальное состояние.

**Comment by Leemellaret** [comment]
Сделано
